import { FeelProdInvoice, KineSession } from '@/types/facturation';

export const INITIAL_FEELPROD_INVOICES: FeelProdInvoice[] = [
  {
    id: 'fp-2026-001',
    number: 'FP-2026-001',
    date: '2026-01-18',
    dueDate: '2026-02-18',
    clientName: 'Atelier Bois & Design',
    clientCompany: 'Atelier Bois SAS',
    clientEmail: 'contact@atelierbois-design.fr',
    projectTitle: 'Teaser Artisans d\'Art & Captation Ébénisterie',
    items: [
      {
        id: 'item-1',
        type: 'tjm_tournage',
        description: 'Tournage en atelier (2 jours) - Cadre cinéma & éclairage',
        quantity: 2,
        unit: 'jour',
        unitPriceHT: 750,
        totalHT: 1500,
      },
      {
        id: 'item-2',
        type: 'forfait_montage',
        description: 'Montage créatif, habillage et sound design teaser 60s',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 1800,
        totalHT: 1800,
      },
      {
        id: 'item-3',
        type: 'materiel',
        description: 'Kit optiques cinéma anamorphiques + éclairage LED Aputure',
        quantity: 1,
        unit: 'unite',
        unitPriceHT: 450,
        totalHT: 450,
      },
    ],
    totalHT: 3750,
    vatRate: 20,
    vatAmount: 750,
    totalTTC: 4500,
    depositAmount: 1350,
    remainingDue: 0,
    status: 'paye',
    accountingAccount: '706000',
    vatAccount: '445710',
    notes: 'Règlement solde reçu par virement le 12/02/2026.',
  },
  {
    id: 'fp-2026-002',
    number: 'FP-2026-002',
    date: '2026-02-14',
    dueDate: '2026-03-14',
    clientName: 'Laboratoire Océan Santé',
    clientCompany: 'Océan Santé SAS',
    clientEmail: 'communication@oceansante.com',
    projectTitle: 'Film institutionnel R&D Algoculture & Biotechnologies',
    items: [
      {
        id: 'item-4',
        type: 'tjm_realisation',
        description: 'Réalisation, direction de production & interviews (3 jours)',
        quantity: 3,
        unit: 'jour',
        unitPriceHT: 850,
        totalHT: 2550,
      },
      {
        id: 'item-5',
        type: 'tjm_drone',
        description: 'Prises de vues aériennes drone homologué S3 littoral (1 jour)',
        quantity: 1,
        unit: 'jour',
        unitPriceHT: 900,
        totalHT: 900,
      },
      {
        id: 'item-6',
        type: 'forfait_montage',
        description: 'Post-production intégrale : montage 4K, étalonnage DaVinci & mixage',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 2600,
        totalHT: 2600,
      },
      {
        id: 'item-7',
        type: 'deplacement_km',
        description: 'Déplacement équipe Bretagne (600 km x 0.40 €)',
        quantity: 600,
        unit: 'km',
        unitPriceHT: 0.4,
        totalHT: 240,
      },
    ],
    totalHT: 6290,
    vatRate: 20,
    vatAmount: 1258,
    totalTTC: 7548,
    depositAmount: 2264.4,
    remainingDue: 0,
    status: 'paye',
    accountingAccount: '706000',
    vatAccount: '445710',
    notes: 'Prestation livrée et validée. Réglé par virement bancaire LCL Pro.',
  },
  {
    id: 'fp-2026-003',
    number: 'FP-2026-003',
    date: '2026-03-22',
    dueDate: '2026-04-22',
    clientName: 'Paris Live Music Fest',
    clientCompany: 'PLMF Production',
    clientEmail: 'direction@parislivefest.fr',
    projectTitle: 'Captation live multicam concerts & Aftermovie officiel',
    items: [
      {
        id: 'item-8',
        type: 'tjm_tournage',
        description: 'Captation concert 3 caméras Sony FX6 (3 soirées)',
        quantity: 3,
        unit: 'jour',
        unitPriceHT: 750,
        totalHT: 2250,
      },
      {
        id: 'item-9',
        type: 'tjm_drone',
        description: 'Vues d\'ambiance drone outdoor homologué scénographie',
        quantity: 1,
        unit: 'jour',
        unitPriceHT: 850,
        totalHT: 850,
      },
      {
        id: 'item-10',
        type: 'forfait_montage',
        description: 'Aftermovie 3 minutes rythmé + 5 Reels Instagram verticaux 9:16',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 2400,
        totalHT: 2400,
      },
    ],
    totalHT: 5500,
    vatRate: 20,
    vatAmount: 1100,
    totalTTC: 6600,
    depositAmount: 2000,
    remainingDue: 0,
    status: 'paye',
    accountingAccount: '706000',
    vatAccount: '445710',
    notes: 'Règlement complet enregistré.',
  },
  {
    id: 'fp-2026-004',
    number: 'FP-2026-004',
    date: '2026-05-10',
    dueDate: '2026-06-10',
    clientName: 'Institut Médical & Tissulaire',
    clientCompany: 'IMT Formations',
    clientEmail: 'contact@imt-formations.org',
    projectTitle: 'Plateforme E-learning : Tournage 4K & Schémas Animés 24h',
    items: [
      {
        id: 'item-11',
        type: 'tjm_tournage',
        description: 'Tournage studio 4K multi-plans & régie prompteur (2 jours)',
        quantity: 2,
        unit: 'jour',
        unitPriceHT: 800,
        totalHT: 1600,
      },
      {
        id: 'item-12',
        type: 'forfait_montage',
        description: 'Montage 12 modules pédagogiques, chapitrage & sous-titrage VTT',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 3000,
        totalHT: 3000,
      },
      {
        id: 'item-13',
        type: 'forfait_etalonnage',
        description: 'Animations anatomiques vectorielles Ligne Claire & incrustations',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 1300,
        totalHT: 1300,
      },
    ],
    totalHT: 5900,
    vatRate: 20,
    vatAmount: 1180,
    totalTTC: 7080,
    depositAmount: 2500,
    remainingDue: 0,
    status: 'paye',
    accountingAccount: '706000',
    vatAccount: '445710',
  },
  {
    id: 'fp-2026-005',
    number: 'FP-2026-005',
    date: '2026-06-25',
    dueDate: '2026-07-25',
    clientName: 'Domaine de la Chesnaie',
    clientCompany: 'Chesnaie Réceptions',
    clientEmail: 'contact@chesnaie-evenements.com',
    projectTitle: 'Clip promotionnel Mariages & Salons d\'Honneur',
    items: [
      {
        id: 'item-14',
        type: 'tjm_drone',
        description: 'Prises de vues drone parc & architecture historique (1.5 j)',
        quantity: 1.5,
        unit: 'jour',
        unitPriceHT: 900,
        totalHT: 1350,
      },
      {
        id: 'item-15',
        type: 'forfait_montage',
        description: 'Montage teaser 90s + version format court LinkedIn / Instagram',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 1200,
        totalHT: 1200,
      },
    ],
    totalHT: 2550,
    vatRate: 20,
    vatAmount: 510,
    totalTTC: 3060,
    depositAmount: 1000,
    remainingDue: 0,
    status: 'paye',
    accountingAccount: '706000',
    vatAccount: '445710',
  },
  {
    id: 'fp-2026-006',
    number: 'FP-2026-006',
    date: '2026-07-15',
    dueDate: '2026-08-30',
    clientName: 'BioTech Innovations',
    clientCompany: 'BioTech SAS',
    clientEmail: 'finance@biotech-innov.fr',
    projectTitle: 'Série Portraits Dirigeants & Témoignages Chercheurs',
    items: [
      {
        id: 'item-16',
        type: 'tjm_tournage',
        description: 'Tournage interviews sur site salle blanche & laboratoires (2 j)',
        quantity: 2,
        unit: 'jour',
        unitPriceHT: 750,
        totalHT: 1500,
      },
      {
        id: 'item-17',
        type: 'forfait_montage',
        description: 'Montage 4 capsules vidéos avec étalonnage et habillage charte graphique',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 1800,
        totalHT: 1800,
      },
      {
        id: 'item-18',
        type: 'deplacement_km',
        description: 'Frais de transport & péages Paris - Lyon',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 180,
        totalHT: 180,
      },
    ],
    totalHT: 3480,
    vatRate: 20,
    vatAmount: 696,
    totalTTC: 4176,
    depositAmount: 1200,
    remainingDue: 2976,
    status: 'partiel',
    accountingAccount: '706000',
    vatAccount: '445710',
    notes: 'Acompte de 1 200 € réglé le 16/07. Facture de solde en attente d\'échéance.',
  },
  {
    id: 'fp-2026-007',
    number: 'FP-2026-007',
    date: '2026-08-20',
    dueDate: '2026-09-20',
    clientName: 'Manufacture Horlogère Prestige',
    clientCompany: 'L\'Atelier Chrono',
    clientEmail: 'marketing@latelierchrono.ch',
    projectTitle: 'Spot Macro Haute Horlogerie & Mouvement Mécanique',
    items: [
      {
        id: 'item-19',
        type: 'tjm_tournage',
        description: 'Tournage macro studio & slider motorisé ultra-précis (2 jours)',
        quantity: 2,
        unit: 'jour',
        unitPriceHT: 900,
        totalHT: 1800,
      },
      {
        id: 'item-20',
        type: 'forfait_etalonnage',
        description: 'Étalonnage haute précision HDR 10 bits DaVinci Resolve',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 1100,
        totalHT: 1100,
      },
      {
        id: 'item-21',
        type: 'forfait_son',
        description: 'Sound design bruits de rouages, tic-tac et mixage Dolby 5.1',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 1000,
        totalHT: 1000,
      },
      {
        id: 'item-22',
        type: 'materiel',
        description: 'Kit optiques Macro Laowa Probe 24mm + éclairage fibre optique',
        quantity: 1,
        unit: 'unite',
        unitPriceHT: 500,
        totalHT: 500,
      },
    ],
    totalHT: 4400,
    vatRate: 20,
    vatAmount: 880,
    totalTTC: 5280,
    depositAmount: 1500,
    remainingDue: 3780,
    status: 'facture',
    accountingAccount: '706000',
    vatAccount: '445710',
    notes: 'Facture émise le 20/08. Échéance le 20/09.',
  },
  {
    id: 'fp-2026-008',
    number: 'FP-2026-008',
    date: '2026-09-05',
    dueDate: '2026-10-05',
    clientName: 'Fondation Art & Sculpture',
    clientCompany: 'Fondation Rodin & Contemporains',
    clientEmail: 'projets@fondation-art.org',
    projectTitle: 'Film documentaire rétrospective bronzes & patines',
    items: [
      {
        id: 'item-23',
        type: 'tjm_realisation',
        description: 'Réalisation et interviews historiens d\'art (3 jours)',
        quantity: 3,
        unit: 'jour',
        unitPriceHT: 800,
        totalHT: 2400,
      },
      {
        id: 'item-24',
        type: 'forfait_montage',
        description: 'Montage film 26 minutes pour projection musée',
        quantity: 1,
        unit: 'forfait',
        unitPriceHT: 2400,
        totalHT: 2400,
      },
    ],
    totalHT: 4800,
    vatRate: 20,
    vatAmount: 960,
    totalTTC: 5760,
    depositAmount: 1728,
    remainingDue: 4032,
    status: 'devis_accepte',
    accountingAccount: '706000',
    vatAccount: '445710',
    notes: 'Devis signé. Acompte de 30% perçu (1 728 € TTC). Tournage prévu fin septembre.',
  },
];

export const INITIAL_KINE_SESSIONS: KineSession[] = [
  {
    id: 'kin-2026-001',
    number: 'KIN-2026-001',
    date: '2026-09-02',
    patientName: 'Martine Laurent',
    patientPhone: '06 12 34 56 78',
    actType: 'hors_nomenclature',
    actLabel: 'Thérapie Manuelle Tissulaire & Libération Dure-mère (HN)',
    sessionCount: 1,
    unitPrice: 70,
    totalAmount: 70,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cb',
    paymentStatus: 'regle',
    accountingAccount: '705000',
    notes: 'Bilan cervicalgie chronique. Reçu mutuelle délivré.',
  },
  {
    id: 'kin-2026-002',
    number: 'KIN-2026-002',
    date: '2026-09-03',
    patientName: 'Thomas Bernard',
    patientPhone: '06 98 76 54 32',
    actType: 'conventionne',
    actLabel: 'Rééducation du rachis & posture (AMK 9.5)',
    sessionCount: 1,
    unitPrice: 20.43,
    totalAmount: 20.43,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'virement',
    paymentStatus: 'regle',
    accountingAccount: '705000',
    notes: 'Ordonnance Dr Martin. Télétransmission FSE effectuée.',
  },
  {
    id: 'kin-2026-003',
    number: 'KIN-2026-003',
    date: '2026-09-04',
    patientName: 'Sophie Vallet',
    patientPhone: '06 45 67 89 01',
    actType: 'hors_nomenclature',
    actLabel: 'Consultation Ostéopathie & Écoute Fasciale (HN)',
    sessionCount: 1,
    unitPrice: 80,
    totalAmount: 80,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cheque',
    paymentStatus: 'regle',
    accountingAccount: '705000',
    notes: 'Chèque N°44892 LCL remis à l\'encaissement.',
  },
  {
    id: 'kin-2026-004',
    number: 'KIN-2026-004',
    date: '2026-09-05',
    patientName: 'Pierre Meunier',
    patientPhone: '07 89 12 34 56',
    actType: 'hors_nomenclature',
    actLabel: 'Thérapie Manuelle Lombaire & Fulcrum Neutral (HN)',
    sessionCount: 1,
    unitPrice: 70,
    totalAmount: 70,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'especes',
    paymentStatus: 'regle',
    accountingAccount: '705000',
    notes: 'Règlement espèces remis avec quittance.',
  },
  {
    id: 'kin-2026-005',
    number: 'KIN-2026-005',
    date: '2026-09-07',
    patientName: 'Claire Dupré',
    patientPhone: '06 23 45 67 89',
    actType: 'conventionne',
    actLabel: 'Rééducation de l\'épaule opérée (AMK 7.5)',
    sessionCount: 1,
    unitPrice: 16.13,
    totalAmount: 16.13,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cb',
    paymentStatus: 'regle',
    accountingAccount: '705000',
  },
  {
    id: 'kin-2026-006',
    number: 'KIN-2026-006',
    date: '2026-09-08',
    patientName: 'Marc Damoiseaux',
    patientPhone: '06 55 44 33 22',
    actType: 'hors_nomenclature',
    actLabel: 'Thérapie Manuelle Fasciale Approfondie (HN)',
    sessionCount: 1,
    unitPrice: 70,
    totalAmount: 70,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cheque',
    paymentStatus: 'differe',
    deferredDepositDate: '2026-09-28',
    accountingAccount: '705000',
    notes: 'Chèque N°782910 à déposer le 28 septembre à sa demande.',
  },
  {
    id: 'kin-2026-007',
    number: 'KIN-2026-007',
    date: '2026-09-09',
    patientName: 'Hélène Giraud',
    patientPhone: '06 87 65 43 21',
    actType: 'hors_nomenclature',
    actLabel: 'Thérapie Manuelle Tissulaire & Axe Crânio-Sacré (HN)',
    sessionCount: 1,
    unitPrice: 70,
    totalAmount: 70,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cb',
    paymentStatus: 'regle',
    accountingAccount: '705000',
  },
  {
    id: 'kin-2026-008',
    number: 'KIN-2026-008',
    date: '2026-09-10',
    patientName: 'Julien Renaud',
    patientPhone: '07 65 43 21 09',
    actType: 'hors_nomenclature',
    actLabel: 'Bilan Postural Global & Séance Tissulaire (HN)',
    sessionCount: 1,
    unitPrice: 80,
    totalAmount: 80,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'virement',
    paymentStatus: 'en_attente',
    accountingAccount: '705000',
    notes: 'RIB transmis, virement en cours de réception.',
  },
  {
    id: 'kin-2026-009',
    number: 'KIN-2026-009',
    date: '2026-09-11',
    patientName: 'Émilie Pasquier',
    patientPhone: '06 33 22 11 00',
    actType: 'conventionne',
    actLabel: 'Rééducation rachis lombaire post-partum (AMK 8.0)',
    sessionCount: 1,
    unitPrice: 17.2,
    totalAmount: 17.2,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'virement',
    paymentStatus: 'regle',
    accountingAccount: '705000',
  },
  {
    id: 'kin-2026-010',
    number: 'KIN-2026-010',
    date: '2026-09-11',
    patientName: 'Lucas Brunet',
    patientPhone: '06 77 88 99 00',
    actType: 'hors_nomenclature',
    actLabel: 'Thérapie Manuelle Tissulaire Épaule & Thorax (HN)',
    sessionCount: 1,
    unitPrice: 75,
    totalAmount: 75,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cb',
    paymentStatus: 'regle',
    accountingAccount: '705000',
  },
  {
    id: 'kin-2026-011',
    number: 'KIN-2026-011',
    date: '2026-09-12',
    patientName: 'Catherine Tessier',
    patientPhone: '06 11 22 33 44',
    actType: 'hors_nomenclature',
    actLabel: 'Thérapie Manuelle Globale (HN)',
    sessionCount: 1,
    unitPrice: 70,
    totalAmount: 70,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cheque',
    paymentStatus: 'regle',
    accountingAccount: '705000',
  },
  {
    id: 'kin-2026-012',
    number: 'KIN-2026-012',
    date: '2026-09-12',
    patientName: 'Patrick Fontaine',
    patientPhone: '06 99 88 77 66',
    actType: 'hors_nomenclature',
    actLabel: 'Séance HN Thérapie Tissulaire Rachis (HN)',
    sessionCount: 1,
    unitPrice: 70,
    totalAmount: 70,
    vatRate: 0,
    vatExemptMention: 'Exonération de TVA, art. 261-4-1° du CGI',
    paymentMethod: 'cb',
    paymentStatus: 'regle',
    accountingAccount: '705000',
  },
];

// Données mensuelles synthétiques pour les graphiques analytiques 2026
export interface MonthlyPerformance {
  month: string; // Jan, Fév, Mar, Avr...
  monthIndex: number;
  feelprodHT: number;
  feelprodTTC: number;
  kineTotal: number;
  totalGlobal: number;
}

export const MONTHLY_PERFORMANCE_2026: MonthlyPerformance[] = [
  { month: 'Janvier', monthIndex: 0, feelprodHT: 3750, feelprodTTC: 4500, kineTotal: 2980, totalGlobal: 6730 },
  { month: 'Février', monthIndex: 1, feelprodHT: 6290, feelprodTTC: 7548, kineTotal: 3410, totalGlobal: 9700 },
  { month: 'Mars', monthIndex: 2, feelprodHT: 5500, feelprodTTC: 6600, kineTotal: 3650, totalGlobal: 9150 },
  { month: 'Avril', monthIndex: 3, feelprodHT: 4200, feelprodTTC: 5040, kineTotal: 3120, totalGlobal: 7320 },
  { month: 'Mai', monthIndex: 4, feelprodHT: 5900, feelprodTTC: 7080, kineTotal: 3580, totalGlobal: 9480 },
  { month: 'Juin', monthIndex: 5, feelprodHT: 2550, feelprodTTC: 3060, kineTotal: 3890, totalGlobal: 6440 },
  { month: 'Juillet', monthIndex: 6, feelprodHT: 3480, feelprodTTC: 4176, kineTotal: 2840, totalGlobal: 6320 },
  { month: 'Août', monthIndex: 7, feelprodHT: 4400, feelprodTTC: 5280, kineTotal: 2150, totalGlobal: 6550 },
  { month: 'Septembre', monthIndex: 8, feelprodHT: 4800, feelprodTTC: 5760, kineTotal: 3920, totalGlobal: 8720 },
];
